### install GitHub packages (tag = commit, branch or release tag)
install.packages("rjags", dependencies = TRUE)
install.packages("RGtk2", dependencies = TRUE)
install.packages("MixSIAR", dependencies = TRUE)
install.packages("remotes", dependencies = TRUE)
remotes::install_github("brianstock/MixSIARgui", dependencies = TRUE)
